### ISSUE TITLE
Undefined index: oauth2state 

### ISSUE THREAD

**Issue by pmaselkowski** [Maslosoft/IlmatarModuleUa#38]
Possible steps to reproduce:

1. Sign-in with oauth as a new user
2. Sign out
3. Sign in as existing user
```

2017/11/07 15:00:22 [error] [php] Undefined index: oauth2state (/var/www/websites/meno.pro/vendor/maslosoft/ilmatar-module-ua/src/Controllers/SsoController.php:57)
Stack trace:
#0 /var/www/websites/meno.pro/vendor/yiisoft/yii/framework/yiilite.php(4177): CInlineAction->runWithParamsInternal()
#1 /var/www/websites/meno.pro/vendor/yiisoft/yii/framework/yiilite.php(3691): CInlineAction->runWithParams()
#2 /var/www/websites/meno.pro/vendor/yiisoft/yii/framework/yiilite.php(6970): Maslosoft\Ilmatar\Modules\Ua\Controllers\SsoController->runAction()
#3 /var/www/websites/meno.pro/vendor/yiisoft/yii/framework/yiilite.php(6979): CFilterChain->run()
#4 /var/www/websites/meno.pro/vendor/yiisoft/yii/framework/yiilite.php(6967): Maslosoft\Ilmatar\Components\Filters\AccessControl->filter()
#5 /var/www/websites/meno.pro/vendor/yiisoft/yii/framework/yiilite.php(6979): CFilterChain->run()
#6 /var/www/websites/meno.pro/vendor/yiisoft/yii/framework/yiilite.php(6967): Maslosoft\Ilmatar\Components\Filters\AjaxOnly->filter()
#7 /var/www/websites/meno.pro/vendor/yiisoft/yii/framework/yiilite.php(6979): CFilterChain->run()
#8 /var/www/websites/meno.pro/vendor/yiisoft/yii/framework/yiilite.php(6967): Maslosoft\Ilmatar\Components\Filters\PostOnly->filter()
#9 /var/www/websites/meno.pro/vendor/yiisoft/yii/framework/yiilite.php(6979): CFilterChain->run()
#10 /var/www/websites/meno.pro/vendor/yiisoft/yii/framework/yiilite.php(6967): Maslosoft\Ilmatar\Components\Filters\Secure->filter()
#11 /var/www/websites/meno.pro/vendor/yiisoft/yii/framework/yiilite.php(3681): CFilterChain->run()
#12 /var/www/websites/meno.pro/vendor/yiisoft/yii/framework/yiilite.php(3666): Maslosoft\Ilmatar\Modules\Ua\Controllers\SsoController->runActionWithFilters()
#13 /var/www/websites/meno.pro/vendor/yiisoft/yii/framework/yiilite.php(1775): Maslosoft\Ilmatar\Modules\Ua\Controllers\SsoController->run()
#14 /var/www/websites/meno.pro/vendor/maslosoft/ilmatar-components/src/Application.php(479): Maslosoft\Ilmatar\Components\Application->runController()
#15 /var/www/websites/meno.pro/vendor/yiisoft/yii/framework/yiilite.php(1212): Maslosoft\Ilmatar\Components\Application->processRequest()
#16 /var/www/websites/meno.pro/vendor/maslosoft/ilmatar-components/src/bootstrap.php(117): Maslosoft\Ilmatar\Components\Application->run()
#17 /var/www/websites/meno.pro/www/index.php(23): require()

```

**Comment by pmaselkowski** [comment]
0bc1ff6
